spring.application.name=auna-backend

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

spring.security.user.name=${NAME_SECURITY}
spring.security.user.password=${PASSWORD_SECURTIY}

app.cors.allowed-origins=${FRONTEND_BASE}


mercadopago.access-token=${MP_ACCESS_TOKEN}